services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    working_dir: /app
    volumes:
      - ./backend/app:/app
      - ./backend/docker-entrypoint.sh:/docker-entrypoint.sh
    ports:
      - "8080:8000"
    environment:
      APP_ENV: dev
      TMDB_API_KEY: ${TMDB_API_KEY}
      TMDB_BASE_URL: ${TMDB_BASE_URL}
    command: ["sh", "/docker-entrypoint.sh"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend  